spring:
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    password:
    jedis:
      pool:
        max-active: 8 # 最大连接数 ( <0 表示无限制)
        max-wait: 1000 # 连接池最大阻塞等待时间 (毫秒)
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
    timeout: 1000 # 连接超时时间 (毫秒)
